var titles = new Array(
  "Herr Professor", 
  "Blue collar working class hero",
  "Defending welter-weight champion", 
  "Country Music Hall of Fame inductee", 
  "Multi-platium recording artist", 
  "Latin Lover",
  "Chancellor of the Exchequer", 
  "Alien Life Form", 
  "Blue plate special",
  "International music sensation", 
  "Daytime Emmy nominee", 
  "Retired electrician", 
  "The artist formerly known as", 
  "Two-time Olympic gold medalist", 
  "Heisman trophy contender", 
  "Undisputed world wrestling champion", 
  "Undersecretary of the Interior", 
  "Perennial favorite", 
  "Former Reform Party presidential nominee", 
  "Retired General", 
  "Former Spice Girl", 
  "Great metropolitan newspaper", 
  "Captain of industry", 
  "Nobel Lauriet", 
  "Two-term Congressman", 
  "Self-help guru", 
  "Slain civil rights leader", 
  "Oscar<SUP>TM</SUP>-nominated supporting actress",
  "Amateur decathalete",
  "Oklahoma death row inmate",
  "Texas oilman",
  "Outgoing Israeli Prime Minister",
  "Senior Fellow at the Brookings Institute",
  "Victims' rights advocate",
  "Former Clinton aide",
  "Outgoing House majority leader",
  "Embattled Secretary of Labor nominee",
  "Second unit production assistant",
  "Louisiana state corrections official",
  "Ousted Panamanian Dictator",
  "Russian-born dental hygenist",
  "Local law enforcement official",
  "U.N. special envoy",
  "Jazz legend",
  "The rogue province of",
  "Number three car company",
  "Harbinger of doom",
  "Real estate novelist who never had time for a wife",
  "Higher education advocate",
  "Former Playmate of the Year",
  "Self-titled debut album",
  "Daydream believer and homecoming queen",
  "Syndicated columnist",
  "Heroic Autobot",
  "Meat packing industry lunimary",
  "Militant guerilla separatist",
  "One-time trucking magnate",
  "Crown Prince of Zydeco",
  "Proud sponsor of XFL football",
  "1980's teen heart throb",
  "The island nation of",
  "Rockefeller Professor of small engine repair",
  "Fugative financier",
  "Isildur's Bane",
  "Funny Man",
  "The comic stylings of",
  "Disinterested third party",
  "Society gadfly",
  "Dark visionary of maladjusted beauty",
  "International fact-finding committee",
  "Opposition figure",
  "Heart-breaker, dream-maker, love-taker",
  "Landmark Supreme Court ruling",
  "Unidentified White House source",
  "Senegalese purveyor of world music",
  "The Love Theme from",
  "Singer-songwriter",
  "The Baton Rouge Law Offices of",
  "Non-printable Character",
  "Ghetto Superstar",
  "Space-age polymer",
  "Today's Tom Sawyer",
  "Ailing Pontiff",
  "First time caller, long time listener",
  "Hairy-handed gent who ran amok in Kent",
  "Rural Route Boxholder",
  "Unclaimed Service Item",
  "The WB\'s",
  "Hip-hop Impresario",
  "Brave o'er-hanging firmament",
  "Seamstress for the band",
  "Caller number 7",
  "Blue canary in the outlet by the light switch",
  "The fake Slim Shady",
  "Minbari not born of Minbar",
  "Roanest of the roan",
  "Hollaback Boy",
  "Young apprentice caught between the Scylla and Charybidis",
  "World's #1 Dad",
  "Silicone sister with a manager mister"
  ""
);

function getTitle() {
  return titles[Math.floor(Math.random() * titles.length)];
}

var quotes = new Array(
  "A thought-provoking and irreverent look at Java, XML, and life.", 
  "The touching story of a young man and his virtual machine.",
  "The feel-good CS course of the year!", 
  "A triumph of the human spirit!",
  "If you only take one Java course this quarter, this should be it!",
  "Based on a true-life story",
  "From the Director of 'The Joy Luck Club' and 'Driving Miss Daisy'",
  "Pauly Shore in his most challenging project yet",
  "Collect all four!",
  "Some cars not for use with some sets",
  "He's so beautiful now, he doesn't wear his shoes.",
  "Introducing a new generation to the genius of Barry Manilow",
  "Strong enough for a man, but pH-balanced for a woman",
  "Same jokes as last term",
  "Refrigerate after opening",
  "CS399J is taped before a live studio audience",
  "CS399J is a healthy part of this nutritious breakfast",
  "Thousands will enter, hundreds will win",
  "Striving to eradicate C++ programs in our lifetime",
  "Yours free with any $40 Estee Lauder purchase",
  "Playing easy listening favorites from the 60's, 70's, and today",
  "And I'll form...the Head!",
  "This space left intentionally blank",
  "Brother Dave's Traveling Salvation Show",
  "Looks like a pump, feels like a sneaker",
  "I've got one word for you, Son: Java"
);

function getQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}
